# Generated by Django 5.1.9 on 2026-08-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ko', models.CharField(help_text='Korean name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True, help_text='Price in KRW', null=True)),
                ('info_level', models.CharField(choices=[('confirmed', 'Confirmed (Public Menu)'), ('pattern', 'General Cooking Pattern'), ('insufficient', 'Insufficient Info')], default='insufficient', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_key', models.CharField(help_text='Key from AllergenChoice', max_length=30)),
                ('likelihood', models.CharField(choices=[('confirmed', 'Confirmed'), ('likely', 'Likely'), ('possible', 'Possible'), ('unlikely', 'Unlikely')], max_length=20)),
                ('source', models.CharField(blank=True, help_text='e.g. public_menu, cooking_pattern, user_feedback', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional context about this allergen')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='menus.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'allergen_key')},
            },
        ),
    ]
