# Generated by Django 5.1.9 on 2026-08-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuallergen',
            name='likelihood',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('likely', 'Likely'), ('possible', 'Possible'), ('none', 'None')], max_length=20),
        ),
    ]
