# Generated by Django 5.1.9 on 2026-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('vi', 'Vietnamese'), ('th', 'Thai'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('ru', 'Russian'), ('id', 'Indonesian'), ('other', 'Other')], default='en', help_text="Used to generate on-site inquiry phrases in the user's language (Step 5 of the plan).", max_length=10),
        ),
    ]
