# Generated by Django 5.1.9 on 2026-08-16 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_provided_info', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10)),
                ('staff_offered_modification', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10)),
                ('info_matched_reality', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10)),
                ('had_reaction', models.BooleanField(default=False)),
                ('reaction_description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='feedback_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visit feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
